import X
assert 3 == X.add(1, 2)
assert 1 == X.sub(3, 2)
assert -1 == X.sub(2, 3)
assert 6 == X.mul(2, 3)
assert 3.5 == X.div(7, 2)
assert 6 == X.calculate_strange_value(1, 2)
assert 2.0 == X.calculate_strange_value(2, 1)
assert 1 == X.calculate_strange_value(2, 2)
assert X.is_valid_positive_integer_input(1)
assert not X.is_valid_positive_integer_input(0)
assert not X.is_valid_positive_integer_input(-1)
assert not X.is_valid_positive_integer_input(1.5)
assert not X.is_valid_positive_integer_input("hello")